name: 'Collect metrics'
description: 'Collect metrics about a job'
inputs:
  url:
    description: 'URL where to post the data'
    required: true
runs:
  using: "node12"
  main: "index.js"
  pre: 'pre.js'
  post: 'post.js'