name: 'Collect metrics'
description: 'Collect metrics about a job'
inputs:
  url:
    description: 'URL where to post the data'
    required: true
  job:
    description: 'Override a job name'
    required: false
  target:
    description: 'Optional "target" tag'
    required: false
runs:
  using: "node12"
  main: "index.js"
  pre: 'pre.js'
  post: 'post.js'